#!/bin/sh
set -e

python3 system/scripts/update_index.py
git add -u system/indexes
git add MANIFEST.md \
  system/indexes/reference-index.md \
  system/indexes/asset-index.md \
  system/indexes/vendor-index.md
python3 system/scripts/update_index.py --check
